#Default Carriers
Carrier.create_or_update(:id => 1, :name => 'AT&T', :extension => '@txt.att.net')
Carrier.create_or_update(:id => 2, :name => 'Boost', :extension => '@myboostmobile.com')
Carrier.create_or_update(:id => 3, :name => 'Cricket', :extension => '@sms.mycricket.com')
Carrier.create_or_update(:id => 4, :name => 'Nextel', :extension => '@messaging.nextel.com')
Carrier.create_or_update(:id => 5, :name => 'T-Mobile', :extension => '@tmomail.net')
Carrier.create_or_update(:id => 6, :name => 'Virgin Mobile', :extension => '@vmobl.com')
Carrier.create_or_update(:id => 7, :name => 'Verizon', :extension => '@vtext.com')
Carrier.create_or_update(:id => 8, :name => 'Sprint', :extension => '@messaging.sprintpcs.com')
Carrier.create_or_update(:id => 9, :name => 'Alltel Wireless', :extension => '@message.alltel.com')